#!/bin/sh
for k in 1 2 3; do
    for i in 32 128 1024 2048; do
        echo "Size=" $i >> "resultados.csv"
        for j in 1 2 3 4 5; do
            ./bin/mmult $i $j
        done
    done
done
echo "Finished."
