#!/bin/sh

# module load gcc/5.3.0
# module load papi/5.4.1

for i in 32 128 1024 2048; do
    echo "Size=" $i >> "resultados.csv"
    for j in 1 2 3 4 5; do
        ./bin/mmult $i $j
    done
done
echo "Finished."
