#!/bin/sh

#PBS -N missl2
#PBS -l walltime=01:30:00
#PBS -l nodes=1:r662:ppn=48

module purge
module load gcc/5.3.0
module load papi/5.4.1

cd $PBS_O_WORKDIR

make

for k in 1 2 3 4 5 6 7 8; do
    for i in 32 128 1024 2048; do
        echo "Size=" $i >> "resultados.csv"
        for j in 1 2 3 4 5; do
            ./bin/mmult $i $j
        done
    done
done
echo "Finished."
